msm8953-mainline/linux

- arch/arm64/boot/dts/qcom/sdm625-xiaomi-daisy.dts
The DT for daisy was missing the nodes for s* regulators so they had no voltage and current set. This prevented the modem from booting and caused some other issues.
I also added basic audio nodes, but there's still work to do.
And i finally added the volume-up button.
> arm64: dts: qcom: sdm625-xiaomi-daisy: New nodes for audio, also added missing s regulators and volume-up button

- Documentation/devicetree/bindings/sound/max9892x.txt
- sound/soc/codecs/max98927.c
- sound/soc/codecs/max98927.h
The max98927 codec on some devices requires pulling a reset gpio before
responding to any i2c command. This commit adds support for it through
an optional reset-gpios property.
I think i clicked the wrong button on the other pr and closed it, here it goes again.
> ASoC: max98927: Handle reset gpio when probing i2c

- arch/arm64/boot/dts/qcom/msm8953-motorola-potter.dts
CD-gpios don't work on potter for whatever reason, so the current solution is to just drop them. Also the touchscreen doesn't work, because the fixed regulator was disabled. @vladly says its better to model this as a reset-gpio in the synaptics driver, but I haven't had the time to do that, so I think its best to simply force the gpio to the on state for now.
> SD Card and touch screen fixes for potter on 5.16

- arch/arm64/boot/dts/qcom/msm8953-motorola-potter.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
- arch/arm64/boot/dts/qcom/sdm450-samsung-a6plte-r4.dts
- arch/arm64/boot/dts/qcom/sdm632-fairphone-fp3.dts
- arch/arm64/boot/dts/qcom/sdm632-motorola-ocean.dts
this will avoid the usage of dummy regulator for the modem remoteproc and avoid a warning message within the dmesg
> arm64: dts: qcom: msm8953: typo fix for modem pll supply

- Documentation/devicetree/bindings/iio/imu/bosch,bmi160.yaml
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-tissot.dts
- drivers/iio/imu/bmi160/bmi160_core.c
- drivers/iio/imu/bmi160/bmi160_i2c.c
- drivers/iio/imu/bmi160/bmi160_spi.c
- Return bmi120
- Add a framebuffer
- Remove the downstream battery node
- Add wip battery and charger node
- Some sound changes
- Add other missing nodes
- Sort alphabetically
> tissot: fixes for 6.0

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
this is just a fixup to keep the vince dts in sync with upstreamed changes here:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts?h=next-20230106
> fixup! arm64: dts: qcom: msm8953: xiaomi-vince: general update

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
- arch/arm64/boot/dts/qcom/sdm625-motorola-potter.dts
- arch/arm64/boot/dts/qcom/sdm625-xiaomi-daisy.dts
- arch/arm64/boot/dts/qcom/sdm625-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/sdm625-xiaomi-tissot.dts
This commit enables Asahi Kasei AK09918 and Liteon ltrf216a for xiaomi-vince. It also add a missing property for battery: constant-charge-current-max-microamp
> arm64: dts: qcom: xiaomi-vince: add magnetometer and light sensor

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-common.dtsi
Currently the digital codec driver does not probe because it depends on wcd_codec, which was disabled on xiaomi devices.
This assumes all xiaomi devices have the same wiring for the audio
> arm64: dts: qcom: msm8953-xiaomi-common: enable wcd_codec

- arch/arm64/boot/dts/qcom/sdm632-motorola-ocean.dts
This assigns 16 levels of brightness for backlight, and sets level 9 as default. In my rather crude test of using phosh's brightness slider, it seemed visually the same as without the levels.
> arm64: dts: qcom: sdm632: motorola-ocean: Add brightness levels

- Documentation/devicetree/bindings/pinctrl/qcom,pmic-gpio.yaml
- arch/arm64/boot/dts/qcom/pm8953.dtsi
- drivers/pinctrl/qcom/pinctrl-spmi-gpio.c
Upstream link:
* https://lore.kernel.org/linux-arm-msm/20230421-pm8953-gpio-v1-0-3d33e2de47e3@z3ntu.xyz/T/
> Add PM8953 GPIO support

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
Here I also attach a working ucm2 profile for vince soundcard.
I will add it to device-xiaomi-vince package.
Tested and working with jack-sensing and media buttons (play/pause from headphones).
Tested and working playback/recording, both with prim and sec mics and with headphones mic
Only 3 notable things:
- it generate a background noise when there's no output signal
- start from a low-level volume. the output is very loud
UCM2:
https://github.com/M0Rf30/msm8953-snd-card-mtp/tree/6.3.0
This UCM can be adapted or generalized to work on all devices without speaker and CS-Voice support
> arm64: dts: qcom: msm8953: xiaomi-vince: enable soundcard

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
Add battery node for mido it enable charging and fix usb networking.
> arm64: dts: qcom: msm8953: xiaomi-mido: add battery info

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
I have enabled sound_card node for mido with proper ucm (modified vince) config almost everything is working.
(speaker, earpiece, mics, headphones, headsetmic, headset control)
[HiFi.conf](https://gist.github.com/barni2000/e8b6bcfb3e1642526f2d0e137d59569c)
[Forked msm8916-mainline/alsa-ucm-conf](https://github.com/barni2000/alsa-ucm-conf)
It also work with original mido HiFi.conf but /usr/share/alsa/ucm2/platforms/msm8916/qdsp6.conf should be modified, CS-Voice lines should be commented out.
In mido HiFi.conf
``` cset "name='RX3 Digital Volume' 115"``` should be modified to ``` cset "name='RX3 Digital Volume' 78"```
> xiaomi-mido: enable soundcard

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-ysl.dts
I have enabled sound_card node for ysl with proper ucm (modified vince) config almost everything is working. It works with mido config.
(speaker, earpiece, mics, headphones, headsetmic)
[HiFi.conf](https://gist.github.com/barni2000/e8b6bcfb3e1642526f2d0e137d59569c)
[Forked msm8916-mainline/alsa-ucm-conf](https://github.com/barni2000/alsa-ucm-conf)
It also work with original mido HiFi.conf but /usr/share/alsa/ucm2/platforms/msm8916/qdsp6.conf should be modified, CS-Voice lines should be commented out.
In mido HiFi.conf
``` cset "name='RX3 Digital Volume' 115"``` should be modified to ``` cset "name='RX3 Digital Volume' 78"```
> xiaomi-ysl: enable soundcard

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
The voltage-max-design-microvolt was incorrectly setted to 4400000. I have corrected to 4380000.
```
POWER_SUPPLY_VOLTAGE_MAX_DESIGN=4380000
```
> xiaomi-mido: set proper voltage-max-design-microvolt

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-tissot.dts
xiaomi-tissot is using external max97220 amplifier for headphones.
This PR define simple-amplifier node for utilize the amplifier.
Other small changes:
- audio-routing
- set back model to xiaomi-tissot
> arm64: dts: qcom: xiaomi-tissot: Add simple-amplifier for headphones

- Documentation/devicetree/bindings/input/qcom,pm8xxx-vib.yaml
- arch/arm64/boot/dts/qcom/pmi632.dtsi
- arch/arm64/boot/dts/qcom/sdm632-fairphone-fp3.dts
- drivers/input/misc/pm8xxx-vibrator.c
Since the patches have been posted on linux-arm-msm and they work fine on Fairphone 3, add the patches to our repo. Should be merged upstream sooner or later.
Also needs `CONFIG_INPUT_PM8XXX_VIBRATOR` config enabled (I use my own defconfig so not sure where to add this)
(note, not tested on 6.4.7 branch really, just directly on v6.5-rc6)
Closes #109
> Add pmi632 vibrator driver

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-tissot.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-ysl.dts
Ysl:
- I have corrected the regulators like in downstream
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/09f6450330b57b8df8b4472917c2d71adc0386d4#diff-1d92316904c11eef1f77aa098cc2b3c418bf8ff1e1fcb7f9fef834f3b8ef0b2eL219-R228
- Added aliases for sdhc_1 and sdhc_2
- I have removed ramoops because it was mapped for wrong address and the address from downstream is overlapping with venus_mem
- I have removed led@0 definition common already define it and device has white led
Mido:
- I have removed wcnss related nodes they are already defined in the msm8953-xiaomi-common
Tissot:
- I have removed duplicated panel nodes
- wcnss_iris has been set to qcom,wcn3680 tissot has 3680b
> Clean ups and fixes for mido, ysl, tissot

- arch/arm64/boot/dts/qcom/Makefile
- arch/arm64/boot/dts/qcom/sdm632-xiaomi-onclite.dts
Add device tree for the Xiaomi Redmi 7.
> arm64: dts: qcom: sdm632: Add device tree for Xiaomi Redmi 7

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-common.dtsi
This integrate the following changes on the commonized device tree:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/arm64/boot/dts/qcom?h=v6.6-rc1&id=b6866546c214aad707f69a7d96215e3d08c2eb84
```
arm64: dts: qcom: msm8953-daisy: use new speaker maxim,interleave-mode
MAX98927 speaker amplifier "interleave_mode" property was never
documented.  Corrected bindings expect "maxim,interleave-mode" instead,
which is already supported by Linux driver.  Change is not compatible
with older Linux kernels.
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230730202051.71099-1-krzysztof.kozlowski@linaro.org
Signed-off-by: Bjorn Andersson <andersson@kernel.org>
``` …
> fixup! arm64: dts: qcom: Commonize msm8953-xiaomi trees

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-ysl.dts
- arch/arm64/boot/dts/qcom/sdm632-xiaomi-onclite.dts
I have find out there were some trailing whitespaces in onclite dts and i forgot to add SPDX header.
I also add copyright comment for ysl and onclite.
> onclite, ysl: Remove trailing whitespaces fix license headers

- drivers/clk/qcom/gcc-msm8953.c
It fixes:
- usb on ysl
- shutdown/reboot
gcc_pcnoc_usb3_axi_clk parent is usb30_master_clk_src.
usb30_master_clk_src -> gcc_pcnoc_usb3_axi_clk -> gcc_usb30_master_clk
> clk: qcom: gcc-msm8953: fix stuck gcc_usb30_master_clk

- arch/arm64/boot/dts/qcom/sdm632-fairphone-fp3.dts
- drivers/gpu/drm/panel/msm8953-generated/panel-fairphone-fp3-hx83112b.c
Two problems resolved:
* Set `prepare_prev_first` flag to fix display init (regression from 6.4, this flag is needed since 6.5)
* Finally resolve panel being stuck on 30Hz, TE signal was not working
And set the iris compatible to fix wifi/bt
> Fix panel and wifi on Fairphone 3

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
Enable bmi160 sensor for mido.
> dts: qcom: msm8953: xiaomi-mido: enable bmi160

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-markw.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-tissot.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-ysl.dts
- arch/arm64/boot/dts/qcom/sdm632-xiaomi-onclite.dts
I have corrected some properties related to wcd_codec, and snd_card, wcnss_iris.
This PR contains fixes for mido, vince, tissot, daisy, markw, ysl and onclite.
> Sound related fixes for xiaomi devices

- Documentation/devicetree/bindings/input/touchscreen/goodix.yaml
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-common.dtsi
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
- drivers/input/touchscreen/goodix.c
Depends on https://github.com/msm8953-mainline/lk2nd/pull/57 for enabling the correct touchscreen according to the display.
Fixes #33
> Add Goodix GT917D touchscreen support for Xiaomi Daisy 

- Documentation/devicetree/bindings/leds/leds-qcom-lpg.yaml
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/pmi8950.dtsi
- drivers/leds/rgb/leds-qcom-lpg.c
This PR add support for irled on xiaomi mido it is based on #96.
For test rc decoders and pwm-ir-tx should be enabled in the config.
It works fine with ir-ctl from v4l-utils
```
```
> Enable irled on xiaomi-mido

- arch/arm64/boot/dts/qcom/sdm450-samsung-a6plte-r4.dts
Similar to Grand Max, A6+ has only one microphone.
> arm64: dts: qcom: sdm450-samsung-a6plte-r4: Use samsung-gmax for &sound_card

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-markw.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
Changes:
- Add ability s5k3l8 use different clock rates
- Enable s5k3l8 for xiaomi-mido
- Enable s5k3l8 for xiaomi-markw
Megapixels config: 
[xiaomi,mido.txt](https://github.com/msm8953-mainline/linux/files/13403241/xiaomi.mido.txt)
> Change the extension to .ini
> Add initial rear camera support for mido and markw

- drivers/gpu/drm/panel/msm8953-generated/panel-xiaomi-ysl-ili7807d.c
With mdp5 ili7807d had some glitches until the first panel off/on, with dpu this issue dissapeard. This commit is a fix for mdp5.
> panel-xiaomi-ysl-ili7807d: fix glitches

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-markw.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-mido.dts
- arch/arm64/boot/dts/qcom/msm8953-xiaomi-vince.dts
For lk2nd touchscreen selection all touchscreen should be disabled by default.
Related lk2nd PR: https://github.com/msm8953-mainline/lk2nd/pull/62
> xiaomi-{markw,mido,vince}: Switch to lk2nd touchscreen selection

- arch/arm64/boot/dts/qcom/Makefile
- arch/arm64/boot/dts/qcom/msm8953-lenovo-kuntao.dts
Lenovo P2 is a handset using the MSM8953 SoC released in 2016
Add a device tree with initial support for:
- GPIO keys
- SDHCI (internal and external storage)
- USB Device Mode
- WCNSS (WiFi/BT)
- Regulators
> arm64: dts: qcom: msm8953-lenovo-kuntao: Add initial device tree

- arch/arm64/boot/dts/qcom/msm8953-xiaomi-daisy.dts
Xiaomi Mi A2 Lite needs qcom,num-strings to be set 3 instead of 2 in pmi8950_wled, this fixes stripes in backlight.
> arm64: dts: qcom: msm8953: xiaomi-daisy: fix backlight stripes

- drivers/net/wireless/ath/ath10k/core.c
This field is introduced in 6.8-rc1 so having it in 6.7.9 makes ath10k fail to build.
> fixup! wifi: ath10k: add support for QCA9379 hw1.0 SDIO

- arch/arm64/boot/dts/qcom/sdm450-xiaomi-rosy.dts
Add i2c sensors for gyroscope (bmi120), accelerometer (ak09918) and ALS (ltr579, no driver support yet).
> rosy: add i2c sensors

- arch/arm64/boot/dts/qcom/msm8953-lenovo-kuntao.dts
- add fuel-gauge, battery, display
- gpio-keys: homepage and one-key-low-power
- accelerometer sensor
- enable pinctrl, lpass and mpss
> arm64: dts: qcom: msm8953: lenovo-kuntao: add fuel-gauge,

- arch/arm64/boot/dts/qcom/Makefile
- arch/arm64/boot/dts/qcom/apq8053-lenovo-cd-18781y.dts
- arch/arm64/boot/dts/qcom/msm8953.dtsi
This adds the device tree for the Lenovo ThinkSmart View (CD-18781Y).
Almost everything is working, except for:
- Proximity and Ambient Light Sensor (see warning in dts file)
- Camera (no driver available)
- Bluetooth Audio (lacking PCM support in upstream sound driver)
Sound support requires patches to the `tas5805m` ASoC codec driver that I'm intending to send upstream sometime soon.
> Add Lenovo ThinkSmart View (CD-18781Y)

- arch/arm64/boot/dts/qcom/msm8953-motorola-potter.dts
- drivers/input/rmi4/rmi_driver.c
- drivers/input/rmi4/rmi_driver.h
- drivers/input/rmi4/rmi_i2c.c
Fixes #220 
Let's test this here before I send it upstream.
> Fix touchscreen initialization on Motorola G5 Plus (Potter)

- arch/arm64/boot/dts/qcom/sdm632-fairphone-fp3.dts
Tested on v6.13 without extra patches, should also be fine in this tree.
https://lore.kernel.org/linux-arm-msm/20250222-fp3-remoteprocs-firmware-v1-0-237ed21c334a@lucaweiss.eu/T/
> Add patches around modem & other remoteprocs for Fairphone 3

- arch/arm64/boot/dts/qcom/Makefile
- arch/arm64/boot/dts/qcom/msm8953-billion-rimob.dts
Billion Capture+ is a handset using the MSM8953 SoC released in 2017
Add a device tree with initial support for:
- GPIO keys
- SDHCI (internal and external storage)
- USB Device Mode
- Regulators
- Simple framebuffer
- Haptics
> arm64: dts: qcom: msm8953: Add device tree for Billion Capture+
